# macos.yml
name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.12.9]
    steps:
      - name: install-cmake
        uses: Symbitic/install-cmake@v0.1.0
        with:
            cmake: 3.20  # Version of CMake to install
            # Version of ninja-build to install
            ninja: # default is 1.9.0
            platform: # optional
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: ${{ matrix.qt_ver }}
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          cmake
          make -j16
