name: MacOS
on: 
  push:
    paths-ignore:
      - 'debian'
      - 'README.md'
      - 'LICENSE'
      - 'buildToVS2019.bat'
  pull_request:
    paths-ignore:
      - 'debian'
      - 'README.md'
      - 'LICENSE'
      - 'buildToVS2019.bat'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.12.11]  # 参考: https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/mac_x64/desktop/qt5_5111
        qt_arch: [clang_64]
    env:
      targetName: PicShot
    steps:
      - name: Cache Qt  # 使用缓存安装Qt模块
        id: cache-qt
        uses: actions/cache@v1  # not v2! 参见 https://github.com/jurplel/install-qt-action
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      
      - name: Install Qt
        if: steps.WindowsCacheQt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          set-env: true
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: pull 3rdparty code
        run: |
          cd ${{github.workspace}}
          git submodule init
          git submodule update
      - name: build macos
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ls -al
          cd bin
          ls -al
      # # 打包
      # - name: package
      #   run: |
      #     # 拷贝依赖
      #     macdeployqt ./${targetName} -qmldir=. -verbose=1 -dmg
      # # 上传artifacts          
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}.zip
      #     path: ./${{ env.targetName }}
      # # tag 上传Release
      # - name: uploadRelease
      #   if: startsWith(github.event.ref, 'refs/tags/')
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./${{ env.targetName }}.dmg
      #     asset_name: ${{ env.targetName }}_${{ matrix.os }}_${{ matrix.qt_ver }}.dmg
      #     tag: ${{ github.ref }}
      #     overwrite: true
