name: MacOS
on: 
  push:
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - '.github/workflows/macos.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.12.10]
        qt_arch: [clang_64]
    env:
      targetName: PicShot
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: pull 3rdparty code
        run: |
          cd ${{github.workspace}}
          git submodule init
          git submodule update
      - name: build macos
        run: |
          cmake .
          make
